name: 01 Test workspace dir for github actions

on: 
  workflow_dispatch:

jobs:
  workspace-print:
    runs-on: ubuntu-latest

    steps:
      - name: print working dir
        run: pwd

      - name: print user
        run: whoami

      - name: print os
        run: cat /etc/os-release
      
