name: 04 Test step outputs

on:
  workflow_dispatch

jobs:
  step-output:
    runs-on: ubuntu-latest

    steps:
      - name: Generate number/output
        id: generate
        run: echo "number=$RANDOM" >> $GITHUB_OUTPUT
      
      - name: print output
        run: echo "Numbe is ${{ toJson(steps.generate.outputs.number)  }}" 
