name: 05 Test job output

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.isBuild.outputs.BUILD }}
    steps:
      - name: build status
        id: isBuild
        run: echo "BUILD=true" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: 
      job1
    steps:
      - name: if build done deploy
      # why needs.job is used why not directly job beacuse jobs run in parallel ydefault but to get output we need them to run after the job1 so we need to use needs keyword to make sure job2 runs after job1 and also to get the output of job1 we need to use needs.job1.outputs.build
        if: needs.job1.outputs.build == 'true'
        run: echo "Deployment allowed"

      - name: print job output
        run: echo "${{needs.job1.outputs.build}}"

      - name: debug step 1
        run: echo "${{ toJson(needs) }}"
      - name: debug step 2
        run: echo "${{ toJson(job) }}"

