name: 05 Test job output

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.isBuild.outputs.BUILD }}
    steps:
      - name: build status
        id: isBuild
        run: echo "BUILD=true" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: 
      job1
    steps:
      - name: if build done deploy
        if: needs.job1.outputs.build == 'true'
        run: echo "Deployment allowed"

      - name: debug step 1
        run: echo "${{ toJson(needs) }}"
      - name: debug step 2
        run: echo "${{ toJson(job) }}"

