name: 11 Test secret variable environment(variable,secret)

on: workflow_dispatch

jobs:
  test_secret_variable:
    runs-on: ubuntu-latest

    steps:
      - name: Print secret and variable
      # for this create variable and secret in UI in reposotory secrets an dvar
      # APP_VERSION: 1

        run: |
          if [[ ${{ vars.APP_VERSION }} == '1' ]]; then echo "Variable is correct: one"; fi
          if [[ ${{ secrets.APP_VERSION }} == '1' ]]; then echo "Secret is correct: one"; fi


  test_specific_env:
    runs-on: ubuntu-latest
    # for this job create dev environmnet 
    # add variable and secret APP_VERSION: 2
    environment: dev
    
    steps:
      - name: print secret and variable for that specific env
        run: |
          if [[ ${{ vars.APP_VERSION }} == '2' ]]; then echo "Variable is correct: two"; fi
          if [[ ${{ secrets.APP_VERSION }} == '2' ]]; then echo "Secret is correct: two"; fi
