name: 13 Cron Job Workflow

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:


jobs:
  cronjob-test:
    runs-on: ubuntu-latest

    steps:
      - name: check time
        run: echo "current time => $(date)"