name: 14.1 Reusable workflow used in 14th workflow (Greeting workflow)

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

    outputs:
      greeting:
        description: "A greeting message"
        value: ${{ jobs.greeting.outputs.message }}

jobs:
  greeting:
    runs-on: ubuntu-latest

    outputs:
      message: ${{ steps.greet.outputs.message }}
    steps:
      - name: generate message
        id: greet
        run: echo "message=Hellow ${{inputs.name}}" >> $GITHUB_OUTPUT


