name: 17 Test failure() in step and job 

on: 
  workflow_dispatch:
    
jobs:
  step-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: build
        run: exit 1 # Simulate failure

      - name: Notify on failure
        if: failure()
        run: echo "The build failed!"

  # Test failure in job
  test:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1 # Fail
  
  notify:
    needs: test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test job failed!"
